version: '3.5'

services:
  app:
    build: .
    command: npm run start
    container_name: payment2-app
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/payment2
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - app
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    container_name: payment2-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment2
      POSTGRES_SCHEMA: public  # Se necessário, ajuste conforme sua configuração
    volumes:
      - ./data:/var/lib/postgresql/data